server:
  port: 8091
  tomcat:
    mbeanregistry:
      enabled: true
    max-connections: 200
    threads:
      max: 150        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10  # 等待队列长度

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

spring:
  datasource:
    username: root
    password: lain_007
    url: jdbc:mysql://110.41.180.185:3306/big_market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Spring 配置；rabbitmq
  rabbitmq:
    addresses: 110.41.180.185
    port: 5672
    username: lain
    password: lain_007
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    topic:
      activity_sku_stock_zero: activity_sku_stock_zero
      send_award: send_award
      send_rebate: send_rebate
      credit_adjust_success: credit_adjust_success
# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy
# Redis
redis:
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
      password: _rem000
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    #    日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: rem-market  # 应用名称
    version: 1.0  # 应用版本
  registry:
    id: nacos-registry  # 注册中心ID
    address: nacos://110.41.180.185:8848  # Nacos注册中心地址
  protocol:
    name: dubbo  # 使用Dubbo协议
    port: -1  # 自动选择端口
  scan:
    base-packages: top.javarem.api  # 扫描指定的包


zookeeper:
  sdk:
    config:
      connect-string: 110.41.180.185:2181
      base-sleep-time-ms: 1000
      max-retries: 3
      session-timeout-ms: 18000
      connection-timeout-ms: 30000

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml